### ISSUE TITLE
SMPL-X pose parameter

### ISSUE THREAD

**Issue by tetora-vision** [GAP-LAB-CUHK-SZ/MVHumanNet#2]
Thank you for your  great work! I have a question about SMPL-X pose parameters. From <outfits_id>/smplx/smpl/xxxxxx.json, I got SMPL-X pose parameters.  But, the length is only 87. SMPL-X has 55 joints (including global-orientation), so the length should be 165. Where does this difference come from?

**Comment by X-zhangyang** [comment]
The issues about the SMPLX parameters should be caused by the save format.  The SMPLX parameters are as follows: 
![image](https://github.com/GAP-LAB-CUHK-SZ/MVHumanNet/assets/33534662/31133134-78ce-4958-9a72-bb60cf8fc989)

Refer to the website for specific details: https://github.com/zju3dv/EasyMocap/blob/master/doc/02_output.md.
