### ISSUE TITLE
Identity ID Available?

### ISSUE THREAD

**Issue by mcbuehler** [GAP-LAB-CUHK-SZ/MVHumanNet#20]
I want to create train and validation splits that have disjoint identities. The annotations provide a `personID` and the smplx parameters an `id` but these values seem to be zero for all sequences (I checked 100 random sequences).

Where can I find the identity for each sequence?

Thank you.

**Comment by JesseLiao00** [comment]
Hi, @mcbuehler . I think the **id**  in smplx parameters or **personID** in openpose means the person id in easymocap estimation process(in this case, id will always be zero due to only one person are in each frame), which has no relationship with our defined subject id(10xxxx or 20xxxx).  If you would want to create train and validation splits, you could use the subject id((10xxxx or 20xxxx) as the unique identifier.

**Comment by mcbuehler** [comment]
Thank you
